version: '3'

services:
  kafka-producer:
    build:
      context: ./
    environment:
      KAFKA_BROKER: 172.11.0.2:9092
    networks:
      - archimicroprojet_kafka_net

networks:
  archimicroprojet_kafka_net:
    external: true
